import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";

type LayoutProp = {
  children: React.ReactNode;
};

const Layout = ({ children }: LayoutProp) => {
  return (
    <>
      <Head>
        <title>Cocktail DB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className="header">
        <Navbar />
      </header>
      <main>{children}</main>
    </>
  );
};

export default Layout;
